"""some changes

Revision ID: 98e6fe1ac196
Revises: 
Create Date: 2024-07-30 10:48:41.789893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e6fe1ac196'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_from_city_to_city_unique', 'connections', ['from_city_id', 'to_city_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_from_city_to_city_unique', 'connections', type_='unique')
    # ### end Alembic commands ###
